name: Build and Push

on:
  push:
    branches:
      - arch-miyo
  schedule:
      # Every Saturday at 1:30AM UTC
      - cron: "30 01 * * 6"
  workflow_dispatch:
   
env:
  # Change these values if you have forked it for your own works
  # Use Lowercase vaue of your Username
  GITHUB_USERNAME: ekkusa
  GITHUB_EMAIL: dayesofficial@gmail.com
  GITHUB_ORG: Miiyo

  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  # Image name and tag. MUST be lowercase
  IMAGE_NAME: docker-image
  IMAGE_TAG: arch-miyo

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configuring git
        run: |
          git config --global user.name $GITHUB_USERNAME
          git config --global user.email $GITHUB_EMAIL
      - name: Logging in to Docker
        run: |
          echo $GITHUB_TOKEN | docker login ghcr.io -u $GITHUB_USERNAME --password-stdin
      - name: Building the Image
        run: |
          docker build -t ghcr.io/${GITHUB_ORG}/${IMAGE_NAME}:${IMAGE_TAG} .
          echo "Build Completed Successfully!"
      - name: Pushing the Image
        run: |
          docker push ghcr.io/${GITHUB_ORG}/${IMAGE_NAME}:${IMAGE_TAG}
