name: Build and Push

on:
  push:
    branches:
      - main
  schedule:
      # Start every 3 days
      - cron: "00 0 */3 * *"
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Push to dockerhub
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: miyouki/arch
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildoptions: "--compress --force-rm"
