name: Build and Push

on:
  workflow_dispatch:
  watch:
    types: [started]
  schedule:
    - cron:  0 0 * * SUN # Start workflows every sunday

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Push to dockerhub
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: miyouki/archlinux
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildoptions: "--compress --force-rm"